// import Head from "next/head";
// import Link from "next/link";
import { FC } from "react";
import Head from "../../node_modules/next/head";
import { NavBar } from "../NavBar";
import styles from "./MainLayout.module.css";

interface Props {
  children?: JSX.Element | JSX.Element[];
}

export const MainLayout: FC<Props> = ({ children }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>About - Camilo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />

      <main className={styles.main}>{children}</main>
    </div>
  );
};
